version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: vet_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
    # Reemplaza esta URL por tu propio dominio o túnel de Ngrok/Localtunnel
      - WEBHOOK_URL=https://coffee-sulfate-unhitched.ngrok-free.dev
      - N8N_HOST=localhost
      - N8N_PORT=5678
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: